### ISSUE TITLE
Does not work on attributes

### ISSUE THREAD

**Issue by michael-o** [fbdo/jaxb2-fixed-value#1]
I have this in my code

```
<xs:attribute name="fuckYouMicrosoft" type="xs:boolean" fixed="true" />
```

to work around a bug in .NET. Unfortuantely, this default value is completely ignored. Can you make this work for attributes too?

**Comment by fbdo** [comment]
Hi Michael, I just saw your message, sorry for the delay. I will check and come back to you. I'm a bit busy last days so be a patient. See you!

**Comment by fbdo** [comment]
Please, check the source code, more precisely the integration test, now you can find a external global binding in jaxb2-fixed-value/src/it/fixedvalue-it/src/main/resources/binding.xjb. I figured out that is possible to have fixed values for attributes using the basic xjc features, without any plugin, you only need to declare the element: 

<jaxb:globalBindings fixedAttributeAsConstantProperty="true" />

Check also the schema.xsd and the Product.java file generated, you can see the attribute with the desired fixed value now.

Thanks to point out this missing feature, I will add a comment in the main page to help others.

**Comment by michael-o** [comment]
Hi Fabio,
sorry for the late response. The IT did the trick. Thank you. The doc update looks good,  though you should link the note about attributes in the first paragraph directly to the heading at the bottom.
